#!/system/bin/sh
exec > /dev/kmsg 2>&1

exit_mounted() {
    setprop halium.datamount.done 1
    exit $1
}

case "$(getprop ro.ubuntu.recovery.fakecache)" in
true|1) : ;;
*) exit_mounted 0 ;;
esac

USERDATA=/dev/block/by-name/userdata
if abm is-multiboot; then
    abm fixup-fstab
    USERDATA=$(awk '$2=="/data" {print $1}' /etc/recovery.fstab)
fi
RETRY_COUNTER=0
while [ $(( RETRY_COUNTER += 1 )) -le 3 ]; do
    mount $USERDATA /data && break || sleep 1
done

if [ $RETRY_COUNTER -eq 4 ]; then
    echo "setup-fake-cache: reached maximum number of retries"
    exit_mounted 1
fi

mkdir /data/cache
mount -o bind /data/cache /cache
exit_mounted 0
